/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhysioRouteImport } from './routes/physio'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhysioIndexRouteImport } from './routes/physio.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PhysioScheduleRouteImport } from './routes/physio.schedule'
import { Route as PhysioReportsRouteImport } from './routes/physio.reports'
import { Route as PhysioPlansRouteImport } from './routes/physio.plans'
import { Route as PhysioPatientsRouteImport } from './routes/physio.patients'
import { Route as PhysioMessagesRouteImport } from './routes/physio.messages'
import { Route as PatientTreatmentRouteImport } from './routes/patient.treatment'
import { Route as PatientTelehealthRouteImport } from './routes/patient.telehealth'
import { Route as PatientProgressRouteImport } from './routes/patient.progress'
import { Route as PatientPaymentsRouteImport } from './routes/patient.payments'
import { Route as PatientMessagesRouteImport } from './routes/patient.messages'
import { Route as PatientExercisesRouteImport } from './routes/patient.exercises'
import { Route as PatientBookRouteImport } from './routes/patient.book'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const PhysioRoute = PhysioRouteImport.update({
  id: '/physio',
  path: '/physio',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysioIndexRoute = PhysioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PhysioRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PhysioScheduleRoute = PhysioScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PhysioRoute,
} as any)
const PhysioReportsRoute = PhysioReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PhysioRoute,
} as any)
const PhysioPlansRoute = PhysioPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => PhysioRoute,
} as any)
const PhysioPatientsRoute = PhysioPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => PhysioRoute,
} as any)
const PhysioMessagesRoute = PhysioMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PhysioRoute,
} as any)
const PatientTreatmentRoute = PatientTreatmentRouteImport.update({
  id: '/treatment',
  path: '/treatment',
  getParentRoute: () => PatientRoute,
} as any)
const PatientTelehealthRoute = PatientTelehealthRouteImport.update({
  id: '/telehealth',
  path: '/telehealth',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProgressRoute = PatientProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPaymentsRoute = PatientPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMessagesRoute = PatientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PatientRoute,
} as any)
const PatientExercisesRoute = PatientExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBookRoute = PatientBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/physio': typeof PhysioRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/exercises': typeof PatientExercisesRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/payments': typeof PatientPaymentsRoute
  '/patient/progress': typeof PatientProgressRoute
  '/patient/telehealth': typeof PatientTelehealthRoute
  '/patient/treatment': typeof PatientTreatmentRoute
  '/physio/messages': typeof PhysioMessagesRoute
  '/physio/patients': typeof PhysioPatientsRoute
  '/physio/plans': typeof PhysioPlansRoute
  '/physio/reports': typeof PhysioReportsRoute
  '/physio/schedule': typeof PhysioScheduleRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/physio/': typeof PhysioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/exercises': typeof PatientExercisesRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/payments': typeof PatientPaymentsRoute
  '/patient/progress': typeof PatientProgressRoute
  '/patient/telehealth': typeof PatientTelehealthRoute
  '/patient/treatment': typeof PatientTreatmentRoute
  '/physio/messages': typeof PhysioMessagesRoute
  '/physio/patients': typeof PhysioPatientsRoute
  '/physio/plans': typeof PhysioPlansRoute
  '/physio/reports': typeof PhysioReportsRoute
  '/physio/schedule': typeof PhysioScheduleRoute
  '/admin': typeof AdminIndexRoute
  '/patient': typeof PatientIndexRoute
  '/physio': typeof PhysioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/physio': typeof PhysioRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/book': typeof PatientBookRoute
  '/patient/exercises': typeof PatientExercisesRoute
  '/patient/messages': typeof PatientMessagesRoute
  '/patient/payments': typeof PatientPaymentsRoute
  '/patient/progress': typeof PatientProgressRoute
  '/patient/telehealth': typeof PatientTelehealthRoute
  '/patient/treatment': typeof PatientTreatmentRoute
  '/physio/messages': typeof PhysioMessagesRoute
  '/physio/patients': typeof PhysioPatientsRoute
  '/physio/plans': typeof PhysioPlansRoute
  '/physio/reports': typeof PhysioReportsRoute
  '/physio/schedule': typeof PhysioScheduleRoute
  '/admin/': typeof AdminIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/physio/': typeof PhysioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/patient'
    | '/physio'
    | '/admin/analytics'
    | '/admin/finance'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/exercises'
    | '/patient/messages'
    | '/patient/payments'
    | '/patient/progress'
    | '/patient/telehealth'
    | '/patient/treatment'
    | '/physio/messages'
    | '/physio/patients'
    | '/physio/plans'
    | '/physio/reports'
    | '/physio/schedule'
    | '/admin/'
    | '/patient/'
    | '/physio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/finance'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/exercises'
    | '/patient/messages'
    | '/patient/payments'
    | '/patient/progress'
    | '/patient/telehealth'
    | '/patient/treatment'
    | '/physio/messages'
    | '/physio/patients'
    | '/physio/plans'
    | '/physio/reports'
    | '/physio/schedule'
    | '/admin'
    | '/patient'
    | '/physio'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/patient'
    | '/physio'
    | '/admin/analytics'
    | '/admin/finance'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/patient/appointments'
    | '/patient/book'
    | '/patient/exercises'
    | '/patient/messages'
    | '/patient/payments'
    | '/patient/progress'
    | '/patient/telehealth'
    | '/patient/treatment'
    | '/physio/messages'
    | '/physio/patients'
    | '/physio/plans'
    | '/physio/reports'
    | '/physio/schedule'
    | '/admin/'
    | '/patient/'
    | '/physio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  PhysioRoute: typeof PhysioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/physio': {
      id: '/physio'
      path: '/physio'
      fullPath: '/physio'
      preLoaderRoute: typeof PhysioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physio/': {
      id: '/physio/'
      path: '/'
      fullPath: '/physio/'
      preLoaderRoute: typeof PhysioIndexRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/physio/schedule': {
      id: '/physio/schedule'
      path: '/schedule'
      fullPath: '/physio/schedule'
      preLoaderRoute: typeof PhysioScheduleRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/physio/reports': {
      id: '/physio/reports'
      path: '/reports'
      fullPath: '/physio/reports'
      preLoaderRoute: typeof PhysioReportsRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/physio/plans': {
      id: '/physio/plans'
      path: '/plans'
      fullPath: '/physio/plans'
      preLoaderRoute: typeof PhysioPlansRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/physio/patients': {
      id: '/physio/patients'
      path: '/patients'
      fullPath: '/physio/patients'
      preLoaderRoute: typeof PhysioPatientsRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/physio/messages': {
      id: '/physio/messages'
      path: '/messages'
      fullPath: '/physio/messages'
      preLoaderRoute: typeof PhysioMessagesRouteImport
      parentRoute: typeof PhysioRoute
    }
    '/patient/treatment': {
      id: '/patient/treatment'
      path: '/treatment'
      fullPath: '/patient/treatment'
      preLoaderRoute: typeof PatientTreatmentRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/telehealth': {
      id: '/patient/telehealth'
      path: '/telehealth'
      fullPath: '/patient/telehealth'
      preLoaderRoute: typeof PatientTelehealthRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/progress': {
      id: '/patient/progress'
      path: '/progress'
      fullPath: '/patient/progress'
      preLoaderRoute: typeof PatientProgressRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/payments': {
      id: '/patient/payments'
      path: '/payments'
      fullPath: '/patient/payments'
      preLoaderRoute: typeof PatientPaymentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/messages': {
      id: '/patient/messages'
      path: '/messages'
      fullPath: '/patient/messages'
      preLoaderRoute: typeof PatientMessagesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/exercises': {
      id: '/patient/exercises'
      path: '/exercises'
      fullPath: '/patient/exercises'
      preLoaderRoute: typeof PatientExercisesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/book': {
      id: '/patient/book'
      path: '/book'
      fullPath: '/patient/book'
      preLoaderRoute: typeof PatientBookRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientBookRoute: typeof PatientBookRoute
  PatientExercisesRoute: typeof PatientExercisesRoute
  PatientMessagesRoute: typeof PatientMessagesRoute
  PatientPaymentsRoute: typeof PatientPaymentsRoute
  PatientProgressRoute: typeof PatientProgressRoute
  PatientTelehealthRoute: typeof PatientTelehealthRoute
  PatientTreatmentRoute: typeof PatientTreatmentRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientBookRoute: PatientBookRoute,
  PatientExercisesRoute: PatientExercisesRoute,
  PatientMessagesRoute: PatientMessagesRoute,
  PatientPaymentsRoute: PatientPaymentsRoute,
  PatientProgressRoute: PatientProgressRoute,
  PatientTelehealthRoute: PatientTelehealthRoute,
  PatientTreatmentRoute: PatientTreatmentRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface PhysioRouteChildren {
  PhysioMessagesRoute: typeof PhysioMessagesRoute
  PhysioPatientsRoute: typeof PhysioPatientsRoute
  PhysioPlansRoute: typeof PhysioPlansRoute
  PhysioReportsRoute: typeof PhysioReportsRoute
  PhysioScheduleRoute: typeof PhysioScheduleRoute
  PhysioIndexRoute: typeof PhysioIndexRoute
}

const PhysioRouteChildren: PhysioRouteChildren = {
  PhysioMessagesRoute: PhysioMessagesRoute,
  PhysioPatientsRoute: PhysioPatientsRoute,
  PhysioPlansRoute: PhysioPlansRoute,
  PhysioReportsRoute: PhysioReportsRoute,
  PhysioScheduleRoute: PhysioScheduleRoute,
  PhysioIndexRoute: PhysioIndexRoute,
}

const PhysioRouteWithChildren =
  PhysioRoute._addFileChildren(PhysioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  PhysioRoute: PhysioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
